Add qAlgorithms find features
rickhelmus/patRoon pull request #116
Opened 2024-10-22 09:09 UTC by ricardo-cunha

Hi Rick,

so, here the first pull request to initiate revisions ;)

Cheers,
Ricardo

2024-10-22 09:57 UTC, rickhelmus commented
Hi Ricardo,

Many thanks!! :-)
I'll try to find some time to review your changes. For now, I wanted to ask if you could try to clean up the commits a bit? I think it's easiest if you rebase your fork, see e.g. https://stackoverflow.com/a/33504534

Thanks,
Rick

2024-10-23 12:13 UTC, ricardo-cunha commented
I rebased and 6 commints were ignored, is as you expected?
Let me know what you think.
Regarding the direct integration of the cpp from qAlgorithms, I agree and tried but I was not able to compile with GCC from RTools somehow.

2024-10-30 10:15 UTC, dahoehn commented
Hi Ricardo, hi Rick,

If you used a version of the main branch before the latest commit (1bc3c7a08e8d1bc5f3c4a770d268049faf0cb1dd), the code was either outdated or not functional. The program now compiles correctly on windows and linux (at least for me).

Just a quick note regarding the default settings: I strongly recommend to change the assumed centroid error from five ppm to 0.25 ppm. 0.25 is still a fairly arbitrary number, but roughly matches the centroid error we observed in our reference data. If a feature is not clearly detected, it tends to have a larger error up to ~0.3 ppm. The main problem here is that we only worked with orbitrap data so far. It is also by no extent a final estimate, some changes we are considering for the binning algorithm could change it significantly.
We chose five in the beginning just to have a number, but it vastly overestimates the error and leads to bad results. 
I'd suggest adding a warning message along the lines of "there is a difference between centroid error and mass tolerance" when a value above 1 is set.

Thanks for implementing our work,
Daniel

2024-10-30 14:07 UTC, rickhelmus commented
Hi Daniel,

Thanks for the heads-up!

2024-12-17 08:24 UTC, dahoehn requested changes
**Review for R/features_qalgorithms.R:**
line 22: 
default is 0.25 ppm
line 24: 
since i am still making major changes to the feature processing output, better give the latest version you tested it with
line 37: 
qAlgorithms sets a default ppm automatically, also consider adding the -log argument to collect processing data
line 75: 
files are overwritten, unless the argument "-skip-existing" is given
line 83: 
Simply omit the ppm argument, the default value is as correct as possible for all orbitrap and tof files i have checked so far. To omit logging, execute with the argument -s.
line 96ff: 
if you want to assume every feature to be M+H or M-H, you forgot to consider that in line 118f. I am not a fan of that approach, and since we are currently working on having qAlgorithms internal componentisation it is somewhat redundant. Also note that the uncertainty is the absolute uncertainty of the feature mass and position, although we might change it to the prediction interval or a more useable value down the line. I assume that you generally want the lower and upper bound of the mass and time dimensions, which is possible by taking the bin ID and checking all points in the region described by binIdxStart and binIdxEnd.

An addendum regarding the ppm setting:
Generally, we do not see a correlation between the prediction interval and the mass of a centroid. This means that while 0.25 ppm scales the error to the correct dimension, the main advantage of working with data-derived uncertainties is lost. If you want qAlgorithms to accept pre-centroided data, i would advise against opening this part of the program to user input; especially since the results started to become unreliable around 1.5 ppm last time i ran a test on that behaviour.

2025-04-12 08:31 UTC, closed without merging